# Generated by Django 3.0.5 on 2020-06-16 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0005_auto_20200616_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avr_score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='number_tests_passed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
