# Generated by Django 3.0.5 on 2020-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0006_auto_20200616_0651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avr_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
    ]
