# Generated by Django 3.0.5 on 2020-07-14 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0008_auto_20200627_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_tests_passed',
        ),
    ]
