# Generated by Django 3.0.5 on 2020-07-14 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0010_user_number_tests_passed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='number_tests_passed',
        ),
    ]
