# Generated by Django 3.0.5 on 2020-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0012_user_number_tests_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
