# Generated by Django 3.0.5 on 2020-07-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_account', '0013_user_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='percent',
            new_name='percent_success',
        ),
        migrations.AlterField(
            model_name='user',
            name='number_tests_passed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
