# Generated by Django 3.0.5 on 2020-06-20 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0002_testresult'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRunDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_details', to='testset.Question')),
                ('test_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_details', to='testset.TestResult')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_details', to='testset.Variant')),
            ],
        ),
    ]
