# Generated by Django 3.0.5 on 2020-06-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0003_testrundetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testresult',
            name='avg_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
