# Generated by Django 3.0.5 on 2020-06-22 21:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0004_auto_20200620_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AddField(
            model_name='testrundetail',
            name='is_correct',
            field=models.BooleanField(null=True),
        ),
    ]
