# Generated by Django 3.0.5 on 2020-06-22 23:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0005_auto_20200622_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='number',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
