# Generated by Django 3.0.5 on 2020-06-24 17:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0006_auto_20200622_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestResultDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testset.Question')),
            ],
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='avg_score',
        ),
        migrations.AddField(
            model_name='testresult',
            name='avr_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='testresult',
            name='datetime_run',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_completed',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.DeleteModel(
            name='TestRunDetail',
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='test_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_result_details', to='testset.TestResult'),
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_run_details', to='testset.Variant'),
        ),
    ]
