# Generated by Django 3.0.5 on 2020-06-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0008_auto_20200626_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='step',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
