# Generated by Django 3.0.5 on 2020-06-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0009_testresult_step'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresult',
            name='step',
        ),
        migrations.AddField(
            model_name='testresultdetail',
            name='step',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
