# Generated by Django 3.0.5 on 2020-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0010_auto_20200627_1343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testresultdetail',
            name='step',
        ),
    ]
