# Generated by Django 3.0.5 on 2020-07-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testset', '0011_remove_testresultdetail_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
    ]
